package ch.aamiguet.advent2025

import org.scalatest.*
import flatspec.*
import matchers.*

class Day07AltSpec extends AnyFlatSpec with should.Matchers:

  val d = Day07Alt()

  val input =
    """|.......S.......
       |...............
       |.......^.......
       |...............
       |......^.^......
       |...............
       |.....^.^.^.....
       |...............
       |....^.^...^....
       |...............
       |...^.^...^.^...
       |...............
       |..^...^.....^..
       |...............
       |.^.^.^.^.^...^.
       |...............""".stripMargin

  "Day 7 alternative" should "count all the splits" in
    d.part1(input).shouldBe(21)

  "Day 7 alternative" should "count all the possible timelines" in
    d.part2(input).shouldBe(40)
