package ch.aamiguet.advent2025

import org.scalatest.*
import flatspec.*
import matchers.*

class Day07Spec extends AnyFlatSpec with should.Matchers:

  val d = Day07()

  val input =
    """|.......S.......
       |...............
       |.......^.......
       |...............
       |......^.^......
       |...............
       |.....^.^.^.....
       |...............
       |....^.^...^....
       |...............
       |...^.^...^.^...
       |...............
       |..^...^.....^..
       |...............
       |.^.^.^.^.^...^.
       |...............""".stripMargin

  "Day 7" should "count all the splits" in
    d.part1(input).shouldBe("21")

  "Day 7" should "count all the possible timelines" in
    d.part2(input).shouldBe("40")
